### ISSUE TITLE
Fix Spacing In new.php

### ISSUE THREAD

**Issue by mahdimay** [megacrypto/btc-simple-wallet#3]
Fix the spacing of the code in new.php

**Comment by mgeorgiou** [comment]
I can quickly take that if that is ok

**Comment by mahdimay** [comment]
For sure

**Comment by mgeorgiou** [comment]
@megacrypto PR ready for review https://github.com/megacrypto/btc-simple-wallet/pull/9

**Comment by mahdimay** [comment]
Thanks for your contribution
