### ISSUE TITLE
Add Graphics To README

### ISSUE THREAD

**Issue by mahdimay** [megacrypto/btc-simple-wallet#5]
Add graphics (such as images) to README.md

**Comment by gabrielbonner** [comment]
@megacrypto Errr, you might want to take a look at how you resolved that merge conflict, looks like the README has some broken links and repetitive text.  :)

**Comment by vishnukumar650** [comment]
I think it has some links which are not opening, please rectify them

**Comment by mahdimay** [comment]
Thanks for notifying me. Fixed the merging problem. 
Thanks for your contribution
